# Site settings
title: Pale Horse Labs
description: Bringing an end to obsolete technology
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pale Horse Labs
user_description:
user_title: Bringing an end to obsolete technology
email: hello@palehorselabs.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
